"""``build_document(registry)``: an OpenAPI 3.1 document built from the registry.

**The path-key template, stated here because the web tier's generated client is
built against it and may not invent it.** One concrete path per registered
operation, keyed ``/api/v1/operations/<the operation's registered name>`` — so
``core.workspace.status`` is the literal key
``/api/v1/operations/core.workspace.status`` and ``apps/web``'s typed client
indexes ``paths["/api/v1/operations/core.workspace.status"]["post"]``. Not a
FastAPI-style ``{name}`` template: one path per operation is what carries each
operation's distinct request and response schemas, and a single templated path
could carry only one of them.

That prefix is the shipped bearer ``api`` surface's own
(``apps/core/src/rheo_app_core/api_routes.py``'s ``POST
/api/v1/operations/{name}``). It is **deliberately not** the ``/internal/v1/``
path the web client actually posts to: the document describes the *operation*
contract — the input model, the output model, the envelope — and both listeners
serve exactly that contract over the same ``dispatch()``, differing only in how
the caller authenticates. Run 0v's finding **F20** records that
``overview.md``'s "the internal listener serves the same routes" is not true of
the paths this repository ships.

**No FastAPI import.** This lives in ``rheo_core`` so ``apps/cli`` can reach it
without depending on ``apps/core``; the schemas are pure pydantic
(``model_json_schema(ref_template="#/components/schemas/{model}")``) and the
document is a plain ``dict`` the caller serialises.

The envelope's ``operation_id`` below is a **nullable uuid**, not the always-null
field it was before run 0c2. ``dispatch()`` mints a ``core.operation`` row for a
declaration carrying ``long_running = True`` and puts its id in the envelope; every
other operation — which is every operation registered in release one — still answers
``null``, so the document has to describe both. Nothing in *this* module mints
anything; what changed is the contract it describes.
"""

from typing import Any, Final

from pydantic import BaseModel

from rheo_core.operations.registry import REGISTRY, OperationRegistry

Schema = dict[str, Any]

OPERATION_PATH_PREFIX: Final = "/api/v1/operations/"
"""The document's path-key prefix; see the module docstring. Changing this breaks
``apps/web``'s generated client, which indexes the emitted keys directly."""

REF_TEMPLATE: Final = "#/components/schemas/{model}"
GENERATED_BANNER: Final = "generated by `make codegen`; do not edit"
"""What ``rheo openapi`` writes into the document's ``x-rheo-generated`` field."""

OPENAPI_VERSION: Final = "3.1.0"
DOCUMENT_TITLE: Final = "rheoStream operations"
DOCUMENT_VERSION: Final = "0"
"""Fixed, not the package version: the document is regenerated and diffed byte for
byte in CI (AC 3), so a value that moves with every release bump would make that
check a release-note detector rather than a contract check."""


def operation_path(name: str) -> str:
    """The document path key for one registered operation name."""
    return f"{OPERATION_PATH_PREFIX}{name}"


def _schema_and_defs(model: type[BaseModel]) -> tuple[Schema, dict[str, Schema]]:
    """``model``'s own schema, and the nested models it referenced, split apart.

    ``model_json_schema`` returns nested models under ``$defs`` with ``$ref``s
    pointing wherever ``ref_template`` says. Lifting ``$defs`` into
    ``components.schemas`` is what makes those refs resolve in the assembled
    document.
    """
    schema: Schema = dict(model.model_json_schema(ref_template=REF_TEMPLATE))
    defs = {name: dict(value) for name, value in schema.pop("$defs", {}).items()}
    return schema, defs


def _merge(components: dict[str, Schema], name: str, schema: Schema) -> None:
    """Record one component schema, refusing a genuine name collision.

    Two operations sharing a model (``core.settings.set`` and
    ``core.settings.set_member`` both take ``SettingWrite`` and return
    ``SettingWritten``) merge to the identical schema and are a no-op. Two
    *different* models with the same class name would
    otherwise silently overwrite each other and hand one operation the other's
    contract, so that case raises rather than emitting a quietly wrong document.
    """
    existing = components.get(name)
    if existing is not None and existing != schema:
        raise ValueError(
            f"two different models are both named {name!r}; the OpenAPI document "
            "keys components by class name and cannot carry both"
        )
    components[name] = schema


def _envelope_schema(result_ref: str) -> Schema:
    """The operation envelope as a response schema, with this operation's own
    output model at ``result``.

    The same three keys ``api_routes.envelope`` builds and the internal operations
    route answers with. ``operation_id`` is a **nullable uuid**: run 0c2's dispatcher
    mints one for a declaration carrying ``long_running = True`` and none for any
    other, so a generated client must be able to read both a uuid and ``null`` there.
    Every operation registered in release one still answers ``null``.

    ``approval_id`` is optional and never ``null``: the envelope carries it only on
    an ``approval_required`` hold (``api_routes.envelope``), so a generated client
    reads it as ``string | undefined``, and its presence is the signal.
    """
    return {
        "type": "object",
        "title": "OperationEnvelope",
        "properties": {
            "state": {"type": "string"},
            "operation_id": {"type": ["string", "null"], "format": "uuid"},
            "approval_id": {"type": "string", "format": "uuid"},
            "result": {"$ref": result_ref},
            "error": {
                "type": "object",
                "properties": {
                    "error_code": {"type": "string"},
                    "error_text": {"type": "string"},
                },
                "required": ["error_code", "error_text"],
            },
        },
        "required": ["state", "operation_id"],
    }


def build_document(registry: OperationRegistry = REGISTRY) -> dict[str, Any]:
    """The OpenAPI 3.1 document for every operation ``registry`` holds.

    Walks the registry in sorted name order so the emitted bytes depend on what is
    registered and not on registration order — which is what makes the CI
    regeneration diff (AC 3) a contract check rather than a startup-order check.
    """
    paths: dict[str, Schema] = {}
    components: dict[str, Schema] = {}
    for name in sorted(registry.names()):
        operation = registry.lookup(name)
        if operation is None:  # pragma: no cover - names() is the registry's own keys
            continue
        declaration = operation.declaration
        input_schema, input_defs = _schema_and_defs(declaration.input_model)
        output_schema, output_defs = _schema_and_defs(declaration.output)
        for nested_name, nested in (*input_defs.items(), *output_defs.items()):
            _merge(components, nested_name, nested)
        input_name = declaration.input_model.__name__
        output_name = declaration.output.__name__
        _merge(components, input_name, input_schema)
        _merge(components, output_name, output_schema)
        paths[operation_path(name)] = {
            "post": {
                "operationId": name,
                "summary": f"{name} ({declaration.safety_class.value})",
                "requestBody": {
                    "required": True,
                    "content": {
                        "application/json": {
                            "schema": {"$ref": REF_TEMPLATE.format(model=input_name)}
                        }
                    },
                },
                "responses": {
                    "200": {
                        "description": "the operation envelope",
                        "content": {
                            "application/json": {
                                "schema": _envelope_schema(
                                    REF_TEMPLATE.format(model=output_name)
                                )
                            }
                        },
                    }
                },
            }
        }
    return {
        "openapi": OPENAPI_VERSION,
        "info": {"title": DOCUMENT_TITLE, "version": DOCUMENT_VERSION},
        "paths": paths,
        "components": {"schemas": components},
    }
