"""``rheo web compose``'s renderer: every installed module's web contribution, as the
TypeScript ``apps/web/src/modules.generated.ts`` holds.

**Installed, not loaded.** :func:`installed_manifests` loads every ``rheo.modules``
entry point :func:`~rheo_core.modules.discovered` finds and never reads the
``modules.installed`` allowlist, because the two answer different questions: compose
asks what this host *could* ship, and the allowlist decides what a deployment
*does* load at runtime. ``module-contract.md`` § Extension points names compose as
reading the first. Nothing is registered either: a manifest is read, not installed.

**Pure and byte-stable.** :func:`render` takes manifests and returns text, with no
timestamp, no path and nothing else about the machine that ran it. Modules are sorted
by ``module_id`` and each ``roles`` set is sorted. The tuples inside a contribution
keep the order the module declared them in: they are already deterministic, and the
navigation order is the order a person sees, which is the module author's call.

**Screens and components are property accesses, never strings**
(``recallatronWeb.screens.browse``, ``<module>Web.components.<Name>``), so a screen a
module forgot to export fails ``tsc`` rather than going missing at runtime.

**The banner is compose's own constant**, not ``rheo_core.operations.GENERATED_BANNER``:
that one says ``make codegen``, and naming the command that actually writes the file is
true however it is invoked. Keeping it here also keeps this run's one core touch the
manifest.
"""

import json
from collections.abc import Iterable, Mapping
from typing import Final

from rheo_core.modules import (
    ManifestInvalid,
    ModuleManifest,
    WebContribution,
    discovered,
    load_entry_point,
)

COMPOSE_BANNER: Final = "generated by `rheo web compose`; do not edit"
COMPOSED_MODULE_SOURCE: Final = "@rheo-stream/web-contract/screen"
"""Where the generated file imports the ``ComposedModule`` type from."""

_INDENT: Final = "  "


class MissingWebPackage(Exception):
    """A composed module's web package is not a dependency of ``apps/web``.

    Caught at compose time, naming the package, so the one hand edit adding a module
    needs is not discovered later as an opaque bundler error.
    """

    def __init__(self, missing: tuple[str, ...]) -> None:
        names = ", ".join(missing)
        super().__init__(
            f"web_package_missing: {names} not in apps/web/package.json dependencies; "
            "add each composed module's web package there and commit the lockfile"
        )
        self.missing = missing


def installed_manifests() -> tuple[ModuleManifest, ...]:
    """Every discovered entry point's manifest, sorted by ``module_id``.

    Each entry point goes through :func:`~rheo_core.modules.load_entry_point`, the
    loader's own per-manifest gates (it loads to a manifest, its id matches its
    entry-point name, it is written against this core's contract version), so a
    module the runtime would refuse to load is refused here rather than composed
    into a build that could never show it.
    """
    manifests: dict[str, ModuleManifest] = {}
    for entry_point in discovered():
        loaded = load_entry_point(entry_point)
        if loaded.module_id in manifests:
            raise ManifestInvalid(
                loaded.module_id, "is published by two installed distributions"
            )
        manifests[loaded.module_id] = loaded
    return tuple(manifests[module_id] for module_id in sorted(manifests))


def check_web_dependencies(
    manifests: Iterable[ModuleManifest], package_json: Mapping[str, object]
) -> None:
    """Refuse, naming each one, a composed ``package_name`` that ``package_json``'s
    ``dependencies`` does not list."""
    dependencies = package_json.get("dependencies")
    declared = set(dependencies) if isinstance(dependencies, Mapping) else set()
    missing = sorted(
        {
            manifest.web.package_name
            for manifest in manifests
            if manifest.web is not None and manifest.web.package_name not in declared
        }
    )
    if missing:
        raise MissingWebPackage(tuple(missing))


def render(manifests: Iterable[ModuleManifest]) -> str:
    """The generated TypeScript for ``manifests``: banner, imports, ``MODULES``."""
    composed: dict[str, WebContribution] = {}
    for manifest in manifests:
        if manifest.module_id in composed:
            raise ValueError(f"module {manifest.module_id!r} is composed twice")
        if manifest.web is not None:
            composed[manifest.module_id] = manifest.web
    bindings: dict[str, str] = {}
    for module_id in sorted(composed):
        binding = _binding(module_id)
        if binding in bindings.values():
            raise ValueError(
                f"module {module_id!r} would import as {binding!r}, which another "
                "composed module already uses"
            )
        bindings[module_id] = binding

    lines = [
        f"// {COMPOSE_BANNER}",
        f"import type {{ ComposedModule }} from {_literal(COMPOSED_MODULE_SOURCE)};",
    ]
    lines += [
        f"import * as {bindings[module_id]} from "
        f"{_literal(composed[module_id].package_name)};"
        for module_id in sorted(composed)
    ]
    lines += ["", "export const MODULES = ["]
    for module_id in sorted(composed):
        lines += _module(module_id, composed[module_id], bindings[module_id])
    lines.append("] as const satisfies readonly ComposedModule[];")
    return "\n".join(lines) + "\n"


def _binding(module_id: str) -> str:
    """``recallatron`` -> ``recallatronWeb``; ``some_module`` -> ``someModuleWeb``."""
    head, *rest = module_id.split("_")
    return head + "".join(part.capitalize() for part in rest) + "Web"


def _literal(value: str) -> str:
    """A TypeScript string literal. JSON's string grammar is a subset of it."""
    return json.dumps(value)


def _object(fields: Iterable[tuple[str, str]]) -> str:
    return "{ " + ", ".join(f"{key}: {value}" for key, value in fields) + " }"


def _array(name: str, items: list[str], depth: int) -> list[str]:
    pad = _INDENT * depth
    if not items:
        return [f"{pad}{name}: [],"]
    return [
        f"{pad}{name}: [",
        *(f"{pad}{_INDENT}{item}," for item in items),
        f"{pad}],",
    ]


def _module(module_id: str, web: WebContribution, binding: str) -> list[str]:
    pad = _INDENT * 2
    navigation = [
        _object(
            (
                ("id", _literal(entry.id)),
                ("label", _literal(entry.label)),
                ("path", _literal(entry.path)),
                (
                    "roles",
                    "["
                    + ", ".join(_literal(role.value) for role in sorted(entry.roles))
                    + "]",
                ),
            )
        )
        for entry in web.navigation
    ]
    routes = [
        _object(
            (
                ("id", _literal(route.id)),
                ("path", _literal(route.path)),
                ("screen", f"{binding}.screens.{route.screen}"),
            )
        )
        for route in web.routes
    ]
    record_views = [
        _object(
            (
                ("recordType", _literal(view.record_type)),
                ("component", f"{binding}.components.{view.component}"),
            )
        )
        for view in web.record_views
    ]
    forms = [
        _object(
            (
                ("operation", _literal(form.operation)),
                ("component", f"{binding}.components.{form.component}"),
            )
        )
        for form in web.forms
    ]
    search_providers = [
        _object(
            (
                ("id", _literal(provider.id)),
                ("operation", _literal(provider.operation)),
            )
        )
        for provider in web.search_providers
    ]
    return [
        f"{_INDENT}{{",
        f"{pad}id: {_literal(module_id)},",
        f"{pad}surface: {_literal(web.surface.surface)},",
        *_array("navigation", navigation, 2),
        *_array("routes", routes, 2),
        *_array("recordViews", record_views, 2),
        *_array("forms", forms, 2),
        *_array("searchProviders", search_providers, 2),
        f"{_INDENT}}},",
    ]
