"""AC 14: both generated artifacts carry a "do not edit" banner.

Run 1a3 adds a third generator, ``rheo web compose``; its banner constant is pinned
here too, against both the renderer's own output and the committed
``modules.generated.ts``.

Modelled on ``tests/test_ignored_artifacts.py``'s shape — one narrow property per
test, asserted against the real file in the checkout. It lives in C5 rather than in
C4 because it asserts on **both** generated files and C5 is the first chunk in which
both exist: C3 emits ``apps/web/src/generated/openapi.json``, C4 emits
``apps/web/src/generated/api-types.ts``.

**Banners only, and deliberately so.** The obvious extra assertion — that
``make codegen`` reproduces both files byte for byte — cannot live here: a pytest
test that shells out to ``make codegen`` needs Node and pnpm, and the ``python`` CI
job (``.github/workflows/repository-checks.yml``) has neither. AC 3's
``make codegen && git diff --exit-code -- apps/web/src/generated`` in the **web**
job is the byte-exact gate, and it is the better one because it runs in the job that
has both toolchains. So this module never invokes ``make``.

**Neither banner is written from memory.** ``openapi.json``'s is the generator's own
constant, imported below so the artifact and the generator cannot drift apart
silently, *and* pinned as the literal the specification fixes, so changing both at
once is still a deliberate act. ``api-types.ts``'s belongs to ``openapi-typescript``
and was copied off the emitted file: the pinned version says "Do not make direct
changes to the file", which is **not** the string "do not edit" — a literal guessed
from the other file's wording would fail.
"""

import json
from pathlib import Path

from rheo_app_cli.web_compose import COMPOSE_BANNER, render
from rheo_core.operations import GENERATED_BANNER

_REPO_ROOT = Path(__file__).resolve().parents[1]

OPENAPI_DOCUMENT = _REPO_ROOT / "apps" / "web" / "src" / "generated" / "openapi.json"
API_TYPES = _REPO_ROOT / "apps" / "web" / "src" / "generated" / "api-types.ts"
COMPOSED_MODULES = _REPO_ROOT / "apps" / "web" / "src" / "modules.generated.ts"

BANNER_FIELD = "x-rheo-generated"

#: The text `spec.md` fixes for the document's own banner field.
OPENAPI_BANNER = "generated by `make codegen`; do not edit"

#: ``openapi-typescript``'s own emitted banner, read off the generated file rather
#: than written from memory. Both sentences are asserted: the first names the
#: generator, the second is the "do not edit" instruction in that tool's wording.
API_TYPES_BANNER_LINES = (
    "This file was auto-generated by openapi-typescript.",
    "Do not make direct changes to the file.",
)

#: How much of ``api-types.ts`` the banner has to appear within. A banner that has
#: drifted into the middle of a 600-line generated file is not a banner; and a
#: substring search over the whole file would also match the same words inside a
#: schema description, which is the vacuous version of this assertion.
API_TYPES_BANNER_WINDOW = 200

#: The text ``rheo web compose`` stamps on ``apps/web/src/modules.generated.ts``,
#: pinned here as a literal for the reason ``OPENAPI_BANNER`` is.
MODULES_BANNER = "generated by `rheo web compose`; do not edit"


def test_the_openapi_document_carries_the_generated_banner() -> None:
    document = json.loads(OPENAPI_DOCUMENT.read_text(encoding="utf-8"))
    assert document.get(BANNER_FIELD) == OPENAPI_BANNER, (
        f"{OPENAPI_DOCUMENT.relative_to(_REPO_ROOT)} does not carry the "
        f"{BANNER_FIELD!r} banner {OPENAPI_BANNER!r}; it is a generated artifact "
        "and is never hand-edited — regenerate it with `make codegen`"
    )


def test_the_document_banner_is_the_generator_s_own_constant() -> None:
    """The artifact's banner and ``rheo openapi``'s constant are the same string.

    Without this, `test_the_openapi_document_carries_the_generated_banner` above
    would keep passing against a stale committed document after the generator's
    own banner changed, and the two would drift apart with nothing to say so.
    """
    assert GENERATED_BANNER == OPENAPI_BANNER, (
        "rheo_core.operations.GENERATED_BANNER has drifted from the banner "
        "spec.md fixes; the generated document would carry the new text on the "
        f"next `make codegen` run: {GENERATED_BANNER!r} != {OPENAPI_BANNER!r}"
    )


def test_the_generated_types_carry_openapi_typescript_s_own_banner() -> None:
    head = API_TYPES.read_text(encoding="utf-8")[:API_TYPES_BANNER_WINDOW]
    missing = [line for line in API_TYPES_BANNER_LINES if line not in head]
    assert not missing, (
        f"{API_TYPES.relative_to(_REPO_ROOT)} does not open with "
        f"openapi-typescript's own banner; missing {missing}. It is a generated "
        "artifact and is never hand-edited — regenerate it with `make codegen`"
    )


def test_the_composed_module_file_opens_with_compose_s_own_banner() -> None:
    """The generator half for ``modules.generated.ts``: the constant is the pinned
    text, and it is the first line ``rheo web compose`` writes."""
    assert COMPOSE_BANNER == MODULES_BANNER, (
        "rheo_app_cli.web_compose.COMPOSE_BANNER has drifted from the pinned "
        f"banner: {COMPOSE_BANNER!r} != {MODULES_BANNER!r}"
    )
    assert render(()).splitlines()[0] == f"// {MODULES_BANNER}"


def test_the_committed_composed_module_file_carries_the_banner() -> None:
    """The on-disk half: the committed file opens with the same banner line."""
    first = COMPOSED_MODULES.read_text(encoding="utf-8").splitlines()[0]
    assert first == f"// {MODULES_BANNER}", (
        f"{COMPOSED_MODULES.relative_to(_REPO_ROOT)} does not open with "
        f"{MODULES_BANNER!r}; it is a generated artifact and is never hand-edited — "
        "regenerate it with `make codegen`"
    )
