"""FR 2's generator half: ``rheo web compose`` renders the composed module file.

Seams under test: ``web_compose.render()`` (manifests in, generated TypeScript out,
pinned by a golden string over fixture manifests that exercise every generated shape —
navigation with default and narrowed roles, routes, a record view, a form, a search
provider, a module with no contribution, and a surface name that is not the module
id); ``installed_manifests()`` reading discovered entry points rather than the
``modules.installed`` allowlist; and the ``rheo web compose`` command's
``package.json`` check, driven through ``rheo_app_cli.main.main`` the way an operator
reaches it.

The fixture ids are ``_probe``-suffixed for the reason ``tests/harness/modules.py``
gives. The golden output is written out in full rather than rebuilt from the fixture,
so a dropped record view, form or search provider is a diff against text a person
wrote, not against a second copy of the renderer.
"""

import json
import subprocess
import sys
import textwrap
from importlib.metadata import EntryPoint
from pathlib import Path

import pydantic
import pytest
from harness.modules import install as _install
from harness.modules import manifest as _manifest
from harness.modules import publish as _publish
from rheo_app_cli.main import main
from rheo_app_cli.web_compose import (
    MissingWebPackage,
    check_web_dependencies,
    installed_manifests,
    render,
)
from rheo_contracts import (
    AuditSpec,
    Idempotency,
    OperationDeclaration,
    Role,
    SafetyClass,
)
from rheo_core.modules import (
    ENTRY_POINT_GROUP,
    FormDeclaration,
    ManifestInvalid,
    NavigationEntry,
    RecordType,
    RecordView,
    SearchProvider,
    WebContribution,
    WebRoute,
    WebSurface,
)

COMPOSE_ID = "compose_probe"
ANOTHER_ID = "another_probe"
QUIET_ID = "quiet_probe"

COMPOSE_PACKAGE = "@rheo-stream/compose-probe-web"
ANOTHER_PACKAGE = "@rheo-stream/another-probe-web"


class _ProbeInput(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra="ignore")

    text: str


class _ProbeOutput(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(frozen=True)

    text: str


def _handler(*args: object, **kwargs: object) -> object:
    return None


def _operation(name: str, safety_class: SafetyClass) -> OperationDeclaration:
    return OperationDeclaration(
        name=name,
        safety_class=safety_class,
        roles=frozenset({Role.OWNER}),
        input_model=_ProbeInput,
        output=_ProbeOutput,
        idempotency=Idempotency.NONE,
        audit=AuditSpec(subject_field=None),
    )


COMPOSE_MANIFEST = _manifest(
    COMPOSE_ID,
    operations=(
        (_operation(f"{COMPOSE_ID}.note.find", SafetyClass.READ), _handler),
        (_operation(f"{COMPOSE_ID}.note.add", SafetyClass.MUTATE), _handler),
    ),
    record_types=(
        RecordType(
            name="note",
            table="notes",
            deletable=False,
            delete_roles=frozenset(),
            exportable=False,
            audience_field=None,
        ),
    ),
    web=WebContribution(
        # The surface name is not the module id, so the golden shows which one the
        # generated ``surface`` field carries.
        surface=WebSurface(surface="compose_ui", host="compose", path="/compose"),
        package_name=COMPOSE_PACKAGE,
        navigation=(
            NavigationEntry(id="home", label="Home", path="/"),
            NavigationEntry(
                id="settings",
                label="Settings",
                path="/settings",
                roles=frozenset({Role.OWNER}),
            ),
        ),
        routes=(
            WebRoute(id="home", path="/", screen="home"),
            WebRoute(id="settings", path="/settings", screen="settings"),
        ),
        record_views=(
            RecordView(record_type=f"{COMPOSE_ID}.note", component="NoteView"),
        ),
        forms=(
            FormDeclaration(operation=f"{COMPOSE_ID}.note.add", component="NoteForm"),
        ),
        search_providers=(
            SearchProvider(id="find", operation=f"{COMPOSE_ID}.note.find"),
        ),
    ),
)

ANOTHER_MANIFEST = _manifest(
    ANOTHER_ID,
    web=WebContribution(
        surface=WebSurface(surface=ANOTHER_ID, host="another", path="/another"),
        package_name=ANOTHER_PACKAGE,
        navigation=(),
        routes=(WebRoute(id="index", path="/", screen="index"),),
        record_views=(),
        forms=(),
        search_providers=(),
    ),
)

QUIET_MANIFEST = _manifest(QUIET_ID)
"""Installed, and contributes nothing: no import, no ``MODULES`` entry."""

GOLDEN = """\
// generated by `rheo web compose`; do not edit
import type { ComposedModule } from "@rheo-stream/web-contract/screen";
import * as anotherProbeWeb from "@rheo-stream/another-probe-web";
import * as composeProbeWeb from "@rheo-stream/compose-probe-web";

export const MODULES = [
  {
    id: "another_probe",
    surface: "another_probe",
    navigation: [],
    routes: [
      { id: "index", path: "/", screen: anotherProbeWeb.screens.index },
    ],
    recordViews: [],
    forms: [],
    searchProviders: [],
  },
  {
    id: "compose_probe",
    surface: "compose_ui",
    navigation: [
      { id: "home", label: "Home", path: "/", roles: ["member", "owner"] },
      { id: "settings", label: "Settings", path: "/settings", roles: ["owner"] },
    ],
    routes: [
      { id: "home", path: "/", screen: composeProbeWeb.screens.home },
      { id: "settings", path: "/settings", screen: composeProbeWeb.screens.settings },
    ],
    recordViews: [
      { recordType: "compose_probe.note", component: composeProbeWeb.components.NoteView },
    ],
    forms: [
      { operation: "compose_probe.note.add", component: composeProbeWeb.components.NoteForm },
    ],
    searchProviders: [
      { id: "find", operation: "compose_probe.note.find" },
    ],
  },
] as const satisfies readonly ComposedModule[];
"""  # noqa: E501 - the generated file's own line lengths, reproduced exactly


def _entry_point(module_id: str, name: str) -> EntryPoint:
    return EntryPoint(
        name=module_id, value=f"{__name__}:{name}", group=ENTRY_POINT_GROUP
    )


COMPOSE_ENTRY_POINT = _entry_point(COMPOSE_ID, "COMPOSE_MANIFEST")
ANOTHER_ENTRY_POINT = _entry_point(ANOTHER_ID, "ANOTHER_MANIFEST")
QUIET_ENTRY_POINT = _entry_point(QUIET_ID, "QUIET_MANIFEST")


# --- render() -------------------------------------------------------------------------


def test_render_matches_the_golden_output() -> None:
    assert render([QUIET_MANIFEST, COMPOSE_MANIFEST, ANOTHER_MANIFEST]) == GOLDEN


def test_render_is_byte_stable_under_any_input_order() -> None:
    forward = render([ANOTHER_MANIFEST, COMPOSE_MANIFEST, QUIET_MANIFEST])
    backward = render([QUIET_MANIFEST, COMPOSE_MANIFEST, ANOTHER_MANIFEST])
    assert forward == backward == render([COMPOSE_MANIFEST, ANOTHER_MANIFEST])


def test_render_with_no_contribution_is_an_empty_module_list() -> None:
    assert render([QUIET_MANIFEST]) == (
        "// generated by `rheo web compose`; do not edit\n"
        'import type { ComposedModule } from "@rheo-stream/web-contract/screen";\n'
        "\n"
        "export const MODULES = [\n"
        "] as const satisfies readonly ComposedModule[];\n"
    )


def test_render_refuses_one_module_composed_twice() -> None:
    with pytest.raises(ValueError, match="'compose_probe' is composed twice"):
        render([COMPOSE_MANIFEST, COMPOSE_MANIFEST])


# --- installed_manifests(): discovered, not allowed -----------------------------------


def test_compose_reads_every_installed_module_not_the_allowlist(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """``modules.installed`` names nothing, and compose still sees all three: the
    allowlist gates what a deployment loads, not what the host could ship."""
    _publish(monkeypatch, QUIET_ENTRY_POINT, COMPOSE_ENTRY_POINT, ANOTHER_ENTRY_POINT)
    _install(monkeypatch)

    manifests = installed_manifests()

    assert [manifest.module_id for manifest in manifests] == [
        ANOTHER_ID,
        COMPOSE_ID,
        QUIET_ID,
    ]


def test_compose_refuses_a_manifest_published_under_another_name(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    _publish(monkeypatch, _entry_point("renamed_probe", "COMPOSE_MANIFEST"))
    with pytest.raises(ManifestInvalid, match="renamed_probe"):
        installed_manifests()


# --- the package.json check -----------------------------------------------------------


def test_a_composed_package_missing_from_package_json_is_refused_by_name() -> None:
    package_json = {"dependencies": {ANOTHER_PACKAGE: "workspace:*", "next": "^16"}}
    with pytest.raises(MissingWebPackage) as excinfo:
        check_web_dependencies(
            [COMPOSE_MANIFEST, ANOTHER_MANIFEST, QUIET_MANIFEST], package_json
        )
    assert excinfo.value.missing == (COMPOSE_PACKAGE,)
    assert COMPOSE_PACKAGE in str(excinfo.value)


def test_every_composed_package_present_passes() -> None:
    package_json = {
        "dependencies": {ANOTHER_PACKAGE: "workspace:*", COMPOSE_PACKAGE: "workspace:*"}
    }
    check_web_dependencies([COMPOSE_MANIFEST, ANOTHER_MANIFEST], package_json)


def test_a_dev_dependency_does_not_count() -> None:
    """The shell imports the package at runtime, so it is a ``dependencies`` entry."""
    package_json = {"devDependencies": {COMPOSE_PACKAGE: "workspace:*"}}
    with pytest.raises(MissingWebPackage):
        check_web_dependencies([COMPOSE_MANIFEST], package_json)


@pytest.fixture
def published(monkeypatch: pytest.MonkeyPatch) -> None:
    _publish(monkeypatch, COMPOSE_ENTRY_POINT, QUIET_ENTRY_POINT)
    _install(monkeypatch)


def _package_json(tmp_path: Path, dependencies: dict[str, str]) -> Path:
    path = tmp_path / "package.json"
    path.write_text(json.dumps({"dependencies": dependencies}), encoding="utf-8")
    return path


@pytest.mark.usefixtures("published")
def test_the_command_refuses_to_write_when_a_package_is_missing(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    out = tmp_path / "modules.generated.ts"
    package_json = _package_json(tmp_path, {"next": "^16"})

    code = main(
        ["web", "compose", "--out", str(out), "--package-json", str(package_json)]
    )

    assert code == 1
    assert COMPOSE_PACKAGE in capsys.readouterr().err
    assert not out.exists()


@pytest.mark.usefixtures("published")
def test_the_command_writes_the_rendered_file_when_every_package_is_present(
    tmp_path: Path,
) -> None:
    out = tmp_path / "src" / "modules.generated.ts"
    package_json = _package_json(tmp_path, {COMPOSE_PACKAGE: "workspace:*"})

    code = main(
        ["web", "compose", "--out", str(out), "--package-json", str(package_json)]
    )

    assert code == 0
    assert out.read_text(encoding="utf-8") == render([COMPOSE_MANIFEST, QUIET_MANIFEST])


@pytest.mark.usefixtures("published")
def test_stdout_skips_the_package_check(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """``--out -`` writes nothing into the tree, so there is no dependency to check —
    which is how the file can be inspected before a module's web package exists."""
    missing = tmp_path / "absent.json"

    code = main(["web", "compose", "--out", "-", "--package-json", str(missing)])

    assert code == 0
    assert capsys.readouterr().out == render([COMPOSE_MANIFEST, QUIET_MANIFEST])


# --- the real Recallatron manifest, without the embedding runtime ---------------------

_WITHOUT_EMBEDDING_RUNTIME = textwrap.dedent(
    """
    import importlib.abc
    import importlib.machinery
    import sys

    RUNTIME = {"fastembed", "onnxruntime"}

    class RefuseRuntime(importlib.abc.MetaPathFinder, importlib.abc.Loader):
        # Found, so a find_spec probe for the extra still answers "installed";
        # executing it is what fails, so only a real import is refused.
        def find_spec(self, name, path=None, target=None):
            if name.split(".")[0] in RUNTIME:
                return importlib.machinery.ModuleSpec(name, self)
            return None

        def create_module(self, spec):
            return None

        def exec_module(self, module):
            raise ImportError(
                f"compose imported the embedding runtime: {module.__name__}"
            )

    sys.meta_path.insert(0, RefuseRuntime())

    from rheo_app_cli.web_compose import installed_manifests, render

    text = render(installed_manifests())
    assert '"@rheo-stream/recallatron-web"' in text, text
    assert "recallatronWeb.screens.browse" in text, text
    leaked = sorted(m for m in sys.modules if m.split(".")[0] in RUNTIME)
    assert not leaked, leaked
    """
)


def test_composing_recallatron_does_not_import_the_embedding_runtime() -> None:
    """Risk 4's mitigation: the CI web job syncs without the ``local-embeddings``
    extra, so reading Recallatron's manifest must not need it.

    ``embedding/local.py`` itself is imported — the manifest's job declarations reach
    it — and it is the model runtime it loads lazily (``fastembed``, and the
    ``onnxruntime`` that carries) that must stay out. A fresh interpreter, because
    another test in this session may already have loaded the runtime; an import hook
    that refuses it, so the failure is the import rather than a later inspection. The
    hook still lets a ``find_spec`` probe see the extra, because the provider registry
    probes for it at import, and a hook that hid it would test the no-extra path only.
    """
    result = subprocess.run(
        [sys.executable, "-c", _WITHOUT_EMBEDDING_RUNTIME],
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, result.stderr
