"""Row mapping over the seven tables in :mod:`rheo_recallatron.storage.tables`.

One frozen row dataclass and one ``insert``/``get`` pair per table, and nothing else:
no eligibility, no permission check, no retention window, no audience narrowing, no
purpose intersection. Those are the service's (Prompts 6-9), and a repository that
knew any of them would be a second place the rules live.

**Every value is the caller's, including the identifiers and the clocks.** Minting a
UUIDv7 here would decide *who* mints, and § A3 has an answer already: an ordinary write
mints in the service, while a validated import supplies preserved ids and timestamps
verbatim. A repository that minted would make the second path a special case of the
first. ``search_tsv`` is the one column no caller supplies — it is generated by the
database from ``title`` and ``body``, so it is absent from the insert and present on
the row read back.

Every function takes the caller's ``Connection`` (a ``UnitOfWork.connection`` the core
handed over) and runs inside its transaction; none commits, and none opens anything.
"""

from collections.abc import Sequence
from dataclasses import dataclass
from datetime import datetime
from uuid import UUID

from sqlalchemy import Connection, insert, select, update
from sqlalchemy.engine import RowMapping

from rheo_recallatron.storage import tables as t


@dataclass(frozen=True, slots=True)
class MemoryRow:
    """One ``recallatron.memory`` row, without its generated ``search_tsv``.

    The lexical vector is a physical retrieval detail the database owns and rebuilds;
    carrying it on the row would invite a caller to compare or copy it, and § A3
    excludes it from export for the same reason.
    """

    id: UUID
    kind: str
    title: str
    body: str
    audience_kind: str
    audience_id: UUID | None
    confidence: float | None
    occurred_at: datetime | None
    recorded_at: datetime
    recorded_by_kind: str
    recorded_by_id: UUID | None
    origin: str
    revision: int
    corrected_at: datetime | None
    superseded_by_id: UUID | None
    invalidated_at: datetime | None
    invalidation_reason: str | None
    source_namespace: str | None
    external_source_key: str | None


def _memory_row(mapping: RowMapping) -> MemoryRow:
    return MemoryRow(
        id=mapping["id"],
        kind=mapping["kind"],
        title=mapping["title"],
        body=mapping["body"],
        audience_kind=mapping["audience_kind"],
        audience_id=mapping["audience_id"],
        confidence=mapping["confidence"],
        occurred_at=mapping["occurred_at"],
        recorded_at=mapping["recorded_at"],
        recorded_by_kind=mapping["recorded_by_kind"],
        recorded_by_id=mapping["recorded_by_id"],
        origin=mapping["origin"],
        revision=mapping["revision"],
        corrected_at=mapping["corrected_at"],
        superseded_by_id=mapping["superseded_by_id"],
        invalidated_at=mapping["invalidated_at"],
        invalidation_reason=mapping["invalidation_reason"],
        source_namespace=mapping["source_namespace"],
        external_source_key=mapping["external_source_key"],
    )


def insert_memory(conn: Connection, row: MemoryRow) -> MemoryRow:
    conn.execute(
        insert(t.memory).values(
            id=row.id,
            kind=row.kind,
            title=row.title,
            body=row.body,
            audience_kind=row.audience_kind,
            audience_id=row.audience_id,
            confidence=row.confidence,
            occurred_at=row.occurred_at,
            recorded_at=row.recorded_at,
            recorded_by_kind=row.recorded_by_kind,
            recorded_by_id=row.recorded_by_id,
            origin=row.origin,
            revision=row.revision,
            corrected_at=row.corrected_at,
            superseded_by_id=row.superseded_by_id,
            invalidated_at=row.invalidated_at,
            invalidation_reason=row.invalidation_reason,
            source_namespace=row.source_namespace,
            external_source_key=row.external_source_key,
        )
    )
    return row


def get_memory(conn: Connection, memory_id: UUID) -> MemoryRow | None:
    mapping = (
        conn.execute(select(t.memory).where(t.memory.c.id == memory_id))
        .mappings()
        .one_or_none()
    )
    return None if mapping is None else _memory_row(mapping)


@dataclass(frozen=True, slots=True)
class MemoryPurposeRow:
    memory_id: UUID
    purpose: str


def insert_memory_purpose(conn: Connection, row: MemoryPurposeRow) -> MemoryPurposeRow:
    conn.execute(
        insert(t.memory_purpose).values(memory_id=row.memory_id, purpose=row.purpose)
    )
    return row


def get_memory_purpose(
    conn: Connection, memory_id: UUID, purpose: str
) -> MemoryPurposeRow | None:
    mapping = (
        conn.execute(
            select(t.memory_purpose).where(
                t.memory_purpose.c.memory_id == memory_id,
                t.memory_purpose.c.purpose == purpose,
            )
        )
        .mappings()
        .one_or_none()
    )
    if mapping is None:
        return None
    return MemoryPurposeRow(memory_id=mapping["memory_id"], purpose=mapping["purpose"])


def list_memory_purposes(conn: Connection, memory_id: UUID) -> tuple[str, ...]:
    """Every purpose one memory carries, in vocabulary order.

    Ordered rather than left to the planner for the same reason
    :func:`list_memory_links` is: a derivation intersects these sets and a caller sees
    the result, so two runs of one request must not answer in two orders.
    """
    rows = conn.execute(
        select(t.memory_purpose.c.purpose)
        .where(t.memory_purpose.c.memory_id == memory_id)
        .order_by(t.memory_purpose.c.purpose)
    ).all()
    return tuple(str(row[0]) for row in rows)


@dataclass(frozen=True, slots=True)
class MemoryEntityRow:
    id: UUID
    kind: str
    name: str
    normalized_name: str
    ref: str | None
    created_at: datetime
    source_namespace: str | None
    external_source_key: str | None


def insert_memory_entity(conn: Connection, row: MemoryEntityRow) -> MemoryEntityRow:
    conn.execute(
        insert(t.memory_entity).values(
            id=row.id,
            kind=row.kind,
            name=row.name,
            normalized_name=row.normalized_name,
            ref=row.ref,
            created_at=row.created_at,
            source_namespace=row.source_namespace,
            external_source_key=row.external_source_key,
        )
    )
    return row


def get_memory_entity(conn: Connection, entity_id: UUID) -> MemoryEntityRow | None:
    mapping = (
        conn.execute(select(t.memory_entity).where(t.memory_entity.c.id == entity_id))
        .mappings()
        .one_or_none()
    )
    if mapping is None:
        return None
    return MemoryEntityRow(
        id=mapping["id"],
        kind=mapping["kind"],
        name=mapping["name"],
        normalized_name=mapping["normalized_name"],
        ref=mapping["ref"],
        created_at=mapping["created_at"],
        source_namespace=mapping["source_namespace"],
        external_source_key=mapping["external_source_key"],
    )


@dataclass(frozen=True, slots=True)
class MemoryMentionRow:
    memory_id: UUID
    entity_id: UUID
    role: str | None


def insert_memory_mention(conn: Connection, row: MemoryMentionRow) -> MemoryMentionRow:
    conn.execute(
        insert(t.memory_mention).values(
            memory_id=row.memory_id, entity_id=row.entity_id, role=row.role
        )
    )
    return row


def get_memory_mention(
    conn: Connection, memory_id: UUID, entity_id: UUID
) -> MemoryMentionRow | None:
    mapping = (
        conn.execute(
            select(t.memory_mention).where(
                t.memory_mention.c.memory_id == memory_id,
                t.memory_mention.c.entity_id == entity_id,
            )
        )
        .mappings()
        .one_or_none()
    )
    if mapping is None:
        return None
    return MemoryMentionRow(
        memory_id=mapping["memory_id"],
        entity_id=mapping["entity_id"],
        role=mapping["role"],
    )


@dataclass(frozen=True, slots=True)
class MemoryLinkRow:
    memory_id: UUID
    ref: str
    relation: str
    created_at: datetime
    supersession_lineage: bool


def insert_memory_link(conn: Connection, row: MemoryLinkRow) -> MemoryLinkRow:
    conn.execute(
        insert(t.memory_link).values(
            memory_id=row.memory_id,
            ref=row.ref,
            relation=row.relation,
            created_at=row.created_at,
            supersession_lineage=row.supersession_lineage,
        )
    )
    return row


def get_memory_link(
    conn: Connection, memory_id: UUID, ref: str, relation: str
) -> MemoryLinkRow | None:
    mapping = (
        conn.execute(
            select(t.memory_link).where(
                t.memory_link.c.memory_id == memory_id,
                t.memory_link.c.ref == ref,
                t.memory_link.c.relation == relation,
            )
        )
        .mappings()
        .one_or_none()
    )
    if mapping is None:
        return None
    return MemoryLinkRow(
        memory_id=mapping["memory_id"],
        ref=mapping["ref"],
        relation=mapping["relation"],
        created_at=mapping["created_at"],
        supersession_lineage=mapping["supersession_lineage"],
    )


def list_memory_links(conn: Connection, memory_id: UUID) -> tuple[MemoryLinkRow, ...]:
    """Every link row owned by one memory, in composite-key order.

    Ordered rather than left to the planner because the eligibility service walks
    these in sequence and denies on the first one that fails: an unordered read would
    make *which* link a refusal came from depend on the plan, and two runs of the same
    request could then charge the shared reference budget differently.
    """
    rows = conn.execute(
        select(t.memory_link)
        .where(t.memory_link.c.memory_id == memory_id)
        .order_by(t.memory_link.c.ref, t.memory_link.c.relation)
    ).mappings()
    return tuple(
        MemoryLinkRow(
            memory_id=row["memory_id"],
            ref=row["ref"],
            relation=row["relation"],
            created_at=row["created_at"],
            supersession_lineage=row["supersession_lineage"],
        )
        for row in rows
    )


@dataclass(frozen=True, slots=True)
class MemoryEmbeddingRow:
    memory_id: UUID
    model_id: str
    dimensions: int
    vector: Sequence[float]
    embedded_at: datetime


def insert_memory_embedding(
    conn: Connection, row: MemoryEmbeddingRow
) -> MemoryEmbeddingRow:
    """Write one embedding row.

    No writer in 1a1 calls this: there is no embedding provider and no dense index
    (§ A3). It exists because § A3's own note says synthetic index-invalidation tests
    may seed rows directly through this repository, and a later run's writer needs the
    same mapping. ``vector`` is passed to Postgres in pgvector's text form, which is
    what an unbounded ``vector`` column accepts without a client-side type.
    """
    conn.execute(
        insert(t.memory_embedding).values(
            memory_id=row.memory_id,
            model_id=row.model_id,
            dimensions=row.dimensions,
            vector=_vector_literal(row.vector),
            embedded_at=row.embedded_at,
        )
    )
    return row


def get_memory_embedding(
    conn: Connection, memory_id: UUID, model_id: str
) -> MemoryEmbeddingRow | None:
    mapping = (
        conn.execute(
            select(t.memory_embedding).where(
                t.memory_embedding.c.memory_id == memory_id,
                t.memory_embedding.c.model_id == model_id,
            )
        )
        .mappings()
        .one_or_none()
    )
    if mapping is None:
        return None
    return MemoryEmbeddingRow(
        memory_id=mapping["memory_id"],
        model_id=mapping["model_id"],
        dimensions=mapping["dimensions"],
        vector=_vector_values(mapping["vector"]),
        embedded_at=mapping["embedded_at"],
    )


def _vector_literal(values: Sequence[float]) -> str:
    """pgvector's own text form, ``[1,2,3]``."""
    return "[" + ",".join(repr(float(value)) for value in values) + "]"


def _vector_values(literal: object) -> tuple[float, ...]:
    """The inverse of :func:`_vector_literal` for the text Postgres hands back."""
    stripped = str(literal).strip().removeprefix("[").removesuffix("]")
    if not stripped:
        return ()
    return tuple(float(part) for part in stripped.split(","))


@dataclass(frozen=True, slots=True)
class SourceReceiptRow:
    representation_type: str
    source_namespace: str
    external_source_key: str
    record_id: UUID | None
    payload_digest: bytes
    state: str
    producer_kind: str
    authority_id: UUID
    principal_account_id: UUID | None
    audience_kind: str
    audience_id: UUID | None
    bound_purpose: str | None
    source_recorded_at: datetime | None
    source_expires_at: datetime | None


def insert_source_receipt(conn: Connection, row: SourceReceiptRow) -> SourceReceiptRow:
    conn.execute(
        insert(t.source_receipt).values(
            representation_type=row.representation_type,
            source_namespace=row.source_namespace,
            external_source_key=row.external_source_key,
            record_id=row.record_id,
            payload_digest=row.payload_digest,
            state=row.state,
            producer_kind=row.producer_kind,
            authority_id=row.authority_id,
            principal_account_id=row.principal_account_id,
            audience_kind=row.audience_kind,
            audience_id=row.audience_id,
            bound_purpose=row.bound_purpose,
            source_recorded_at=row.source_recorded_at,
            source_expires_at=row.source_expires_at,
        )
    )
    return row


def set_source_receipt_state(
    conn: Connection,
    representation_type: str,
    source_namespace: str,
    external_source_key: str,
    *,
    state: str,
) -> bool:
    """Move one receipt to a terminal ``state``; answer whether a row was matched.

    The **only** column this updates. Every other column on the row is immutable
    authority context or the digest of the evidence it was accepted under, and
    rewriting either would make a receipt say the unit was accepted under conditions
    it was not — which is the one thing the row exists to remember.
    """
    result = conn.execute(
        update(t.source_receipt)
        .where(
            t.source_receipt.c.representation_type == representation_type,
            t.source_receipt.c.source_namespace == source_namespace,
            t.source_receipt.c.external_source_key == external_source_key,
        )
        .values(state=state)
    )
    return result.rowcount == 1


def get_source_receipt(
    conn: Connection,
    representation_type: str,
    source_namespace: str,
    external_source_key: str,
) -> SourceReceiptRow | None:
    mapping = (
        conn.execute(
            select(t.source_receipt).where(
                t.source_receipt.c.representation_type == representation_type,
                t.source_receipt.c.source_namespace == source_namespace,
                t.source_receipt.c.external_source_key == external_source_key,
            )
        )
        .mappings()
        .one_or_none()
    )
    if mapping is None:
        return None
    return SourceReceiptRow(
        representation_type=mapping["representation_type"],
        source_namespace=mapping["source_namespace"],
        external_source_key=mapping["external_source_key"],
        record_id=mapping["record_id"],
        payload_digest=bytes(mapping["payload_digest"]),
        state=mapping["state"],
        producer_kind=mapping["producer_kind"],
        authority_id=mapping["authority_id"],
        principal_account_id=mapping["principal_account_id"],
        audience_kind=mapping["audience_kind"],
        audience_id=mapping["audience_id"],
        bound_purpose=mapping["bound_purpose"],
        source_recorded_at=mapping["source_recorded_at"],
        source_expires_at=mapping["source_expires_at"],
    )
