"""Row mapping over the tables in :mod:`rheo_recallatron.storage.tables`.

One frozen row dataclass per table and the statements the service needs over it —
``insert``/``get``, the ordered ``list`` reads, and the lifecycle's own narrow
``update``/``delete`` writers — and nothing else: no eligibility, no permission
check, no retention window, no audience narrowing, no purpose intersection, and no
traversal. Those are the service's, and a repository that knew any of them would be
a second place the rules live. Each writer here changes the columns its name says
and leaves every other one alone, which is what keeps "what a correction may touch"
readable from one function rather than from a diff.

**Every value is the caller's, including the identifiers and the clocks.** Minting a
UUIDv7 here would decide *who* mints, and § A3 has an answer already: an ordinary write
mints in the service, while a validated import supplies preserved ids and timestamps
verbatim. A repository that minted would make the second path a special case of the
first. ``search_tsv`` is the one column no caller supplies — it is generated by the
database from ``title`` and ``body``, so it is absent from the insert and present on
the row read back.

Every function takes the caller's ``Connection`` (a ``UnitOfWork.connection`` the core
handed over) and runs inside its transaction; none commits, and none opens anything.
"""

from collections.abc import Sequence
from dataclasses import dataclass
from datetime import datetime
from typing import Final
from uuid import UUID

from sqlalchemy import (
    ColumnElement,
    Connection,
    Float,
    and_,
    bindparam,
    delete,
    func,
    insert,
    literal_column,
    select,
    text,
    true,
    update,
)
from sqlalchemy.dialects.postgresql import insert as pg_insert
from sqlalchemy.engine import RowMapping

from rheo_recallatron.storage import tables as t


@dataclass(frozen=True, slots=True)
class MemoryRow:
    """One ``recallatron.memory`` row, without its generated ``search_tsv``.

    The lexical vector is a physical retrieval detail the database owns and rebuilds;
    carrying it on the row would invite a caller to compare or copy it, and § A3
    excludes it from export for the same reason.
    """

    id: UUID
    kind: str
    title: str
    body: str
    audience_kind: str
    audience_id: UUID | None
    confidence: float | None
    occurred_at: datetime | None
    recorded_at: datetime
    recorded_by_kind: str
    recorded_by_id: UUID | None
    origin: str
    revision: int
    corrected_at: datetime | None
    superseded_by_id: UUID | None
    invalidated_at: datetime | None
    invalidation_reason: str | None
    source_namespace: str | None
    external_source_key: str | None


def _memory_row(mapping: RowMapping) -> MemoryRow:
    return MemoryRow(
        id=mapping["id"],
        kind=mapping["kind"],
        title=mapping["title"],
        body=mapping["body"],
        audience_kind=mapping["audience_kind"],
        audience_id=mapping["audience_id"],
        confidence=mapping["confidence"],
        occurred_at=mapping["occurred_at"],
        recorded_at=mapping["recorded_at"],
        recorded_by_kind=mapping["recorded_by_kind"],
        recorded_by_id=mapping["recorded_by_id"],
        origin=mapping["origin"],
        revision=mapping["revision"],
        corrected_at=mapping["corrected_at"],
        superseded_by_id=mapping["superseded_by_id"],
        invalidated_at=mapping["invalidated_at"],
        invalidation_reason=mapping["invalidation_reason"],
        source_namespace=mapping["source_namespace"],
        external_source_key=mapping["external_source_key"],
    )


def insert_memory(conn: Connection, row: MemoryRow) -> MemoryRow:
    conn.execute(
        insert(t.memory).values(
            id=row.id,
            kind=row.kind,
            title=row.title,
            body=row.body,
            audience_kind=row.audience_kind,
            audience_id=row.audience_id,
            confidence=row.confidence,
            occurred_at=row.occurred_at,
            recorded_at=row.recorded_at,
            recorded_by_kind=row.recorded_by_kind,
            recorded_by_id=row.recorded_by_id,
            origin=row.origin,
            revision=row.revision,
            corrected_at=row.corrected_at,
            superseded_by_id=row.superseded_by_id,
            invalidated_at=row.invalidated_at,
            invalidation_reason=row.invalidation_reason,
            source_namespace=row.source_namespace,
            external_source_key=row.external_source_key,
        )
    )
    return row


def get_memory(conn: Connection, memory_id: UUID) -> MemoryRow | None:
    mapping = (
        conn.execute(select(t.memory).where(t.memory.c.id == memory_id))
        .mappings()
        .one_or_none()
    )
    return None if mapping is None else _memory_row(mapping)


def correct_memory(
    conn: Connection,
    memory_id: UUID,
    *,
    title: str,
    body: str,
    confidence: float | None,
    revision: int,
    corrected_at: datetime,
) -> None:
    """Write a correction's five columns in place, and no others.

    ``search_tsv`` is generated from ``title`` and ``body``, so the database rebuilds
    it with this statement; there is no second write to keep it in step.
    """
    conn.execute(
        update(t.memory)
        .where(t.memory.c.id == memory_id)
        .values(
            title=title,
            body=body,
            confidence=confidence,
            revision=revision,
            corrected_at=corrected_at,
        )
    )


def invalidate_memory(
    conn: Connection,
    memory_id: UUID,
    *,
    reason: str,
    invalidated_at: datetime,
    revision: int,
    superseded_by_id: UUID | None = None,
) -> None:
    """Mark one row invalidated, at its new revision, in the caller's transaction.

    ``superseded_by_id`` is written by the supersession path and left alone by every
    other one: the column names the *replacement*, and a row invalidated because a
    source was corrected has none. The paired ``invalidated_at``/
    ``invalidation_reason`` are written together because the table's own check
    constraint refuses one without the other.
    """
    values: dict[str, object] = {
        "invalidated_at": invalidated_at,
        "invalidation_reason": reason,
        "revision": revision,
    }
    if superseded_by_id is not None:
        values["superseded_by_id"] = superseded_by_id
    conn.execute(update(t.memory).where(t.memory.c.id == memory_id).values(**values))


def delete_memory(conn: Connection, memory_id: UUID) -> bool:
    """Physically remove one memory; answer whether a row was there to remove.

    Its purposes, mentions, links and embeddings go with it through their own
    ``ON DELETE CASCADE``; a predecessor naming it as successor keeps its row and
    loses the pointer, through ``superseded_by_id``'s ``ON DELETE SET NULL``. The
    boolean is what lets the caller count **distinct physically removed rows** rather
    than rows it asked about — a row already absent must not reach the ledger's
    counter.
    """
    result = conn.execute(delete(t.memory).where(t.memory.c.id == memory_id))
    return result.rowcount == 1


def delete_memory_embeddings(conn: Connection, memory_id: UUID) -> None:
    """Remove every embedding of one memory, whatever model wrote it."""
    conn.execute(
        delete(t.memory_embedding).where(t.memory_embedding.c.memory_id == memory_id)
    )


_LEXEME_FREQUENCIES: Final = text(
    """
    WITH stats AS MATERIALIZED (
        SELECT most_common_elems::text::text[] AS elems,
               most_common_elem_freqs AS freqs
        FROM pg_stats
        WHERE schemaname = :schema
          AND tablename = :table
          AND attname = :column
          AND NOT inherited
    )
    SELECT e.lexeme, (s.freqs[1:array_length(s.elems, 1)])[e.position] AS frequency
    FROM stats AS s
    CROSS JOIN LATERAL unnest(s.elems) WITH ORDINALITY AS e(lexeme, position)
    WHERE e.lexeme = ANY(:lexemes)
    """
)
"""The MCELEM lookup, with its three traps handled.

``most_common_elems`` is ``anyarray`` and only reaches ``text[]`` through ``text``; a
direct ``::text[]`` raises. ``most_common_elem_freqs`` carries two trailing entries
past the lexemes (the minimum and maximum frequency), so it is sliced to the lexeme
count rather than zipped to its end. And the cast runs once, in a materialized CTE:
the ``generate_subscripts`` shape re-evaluates it per subscript and costs 226 ms
against 1.4 ms at a full 1,000-entry list, with identical results.
"""


def lexeme_document_frequencies(
    conn: Connection, lexemes: Sequence[str]
) -> dict[str, float]:
    """The sampled fraction of memories whose ``search_tsv`` holds each lexeme.

    Read from ``pg_stats`` for the ``search_tsv`` column, which ``ANALYZE`` and
    autovacuum maintain. A lexeme **absent from the result** is below the statistics'
    tracking floor, or the table has never been analyzed: the caller treats it as rare.
    The values are sample estimates, so one near a threshold may land either side of it
    between analyses.
    """
    if not lexemes:
        return {}
    rows = conn.execute(
        _LEXEME_FREQUENCIES,
        {
            "schema": t.memory.schema,
            "table": t.memory.name,
            "column": t.memory.c.search_tsv.name,
            "lexemes": list(lexemes),
        },
    ).all()
    return {str(lexeme): float(frequency) for lexeme, frequency in rows}


@dataclass(frozen=True, slots=True)
class ExpiredRoot:
    """One memory the retention sweep selected, and the replacement it was retired for.

    ``retained_successor_id`` is the row's own ``superseded_by_id`` and is ``None``
    for a memory nothing replaced. The sweep copies it onto the deletion ledger's
    ``retained_successor_ref``, which § A7 words as *expiring A records
    ``retention_expiry`` and ``retained_successor_ref = B`` before removing A* — an
    identifier-only chain in the deletion evidence, so a later reader can follow a
    supersession across generations neither of whose rows is there any more.
    """

    id: UUID
    retained_successor_id: UUID | None


_SWEEPABLE_AUDIENCE, _ = t.AUDIENCE_KINDS
"""``workspace``. The only audience age-based expiry reaches (§ A9).

Taken off the table's own vocabulary rather than written out, so the predicate and the
column's check constraint cannot drift apart.
"""


def _expired_workspace_memory(horizon: datetime) -> ColumnElement[bool]:
    """§ A9's expiry predicate: a workspace-audience row past ``horizon``.

    **One expression, two callers, and that is the point.** The batch selects roots
    with it and the batch-end remainder check asks ``EXISTS`` with it; if the two
    disagreed, a sweep could select nothing and still find a remainder, rearm a second
    later, and do that for ever.

    Member-audience rows are outside the mechanism at any age: the sweep runs
    accountless and could not authorize erasing member-private content, and a
    workspace operator's data-minimization setting is not authority over one member's
    own record. Their removal path is the ordinary approved deletion, which § A8 lets
    the owner authorize content-free.
    """
    return and_(
        t.memory.c.audience_kind == _SWEEPABLE_AUDIENCE,
        t.memory.c.recorded_at < horizon,
    )


def list_expired_memory_roots(
    conn: Connection, *, horizon: datetime, limit: int
) -> tuple[ExpiredRoot, ...]:
    """At most ``limit`` **workspace-audience** memories recorded before ``horizon``,
    oldest first.

    ``<``, never ``<=``: § A9 retains the boundary instant, so a memory recorded
    exactly on the horizon is still readable and is not selected here.

    ``ORDER BY (recorded_at, id)`` is § A9's, and it is the same pair the
    ``memory_recorded_at_id`` index carries, so the ordering costs a range scan rather
    than a sort of the whole table. Oldest first also means a backlog drains in the
    order it accumulated instead of a batch re-picking rows a previous one skipped.

    **These are *roots*, not a closure.** ``limit`` bounds how many the caller will
    hand to the coordinator one at a time; each one's own ordinary dependants go with
    it and are not counted against the bound. A root that an earlier root in the same
    batch already removed as a dependant is simply absent by the time its turn comes,
    and the coordinator skips it. A member-audience row may still be removed here as
    somebody else's ordinary dependant; what it may never be is a root.
    """
    rows = conn.execute(
        select(t.memory.c.id, t.memory.c.superseded_by_id)
        .where(_expired_workspace_memory(horizon))
        .order_by(t.memory.c.recorded_at, t.memory.c.id)
        .limit(limit)
    ).all()
    return tuple(ExpiredRoot(row.id, row.superseded_by_id) for row in rows)


def expired_memory_exists(conn: Connection, *, horizon: datetime) -> bool:
    """Whether any expirable memory is recorded before ``horizon``. An ``EXISTS``.

    § A9's batch-end remainder check: the sweep needs to know *whether* to ask for
    another batch and explicitly does not store how many are left, so the statement
    stops at the first row rather than counting a backlog nobody records. Same
    predicate as the selection above, for the reason given there.
    """
    return bool(
        conn.execute(
            select(
                select(t.memory.c.id).where(_expired_workspace_memory(horizon)).exists()
            )
        ).scalar_one()
    )


def set_memory_successor(
    conn: Connection, memory_id: UUID, successor_id: UUID | None
) -> None:
    """Point one predecessor at its successor, and nothing else.

    Restore's second pass, and only restore's second pass. Parents go in with a null
    self-reference because a successor may be written after its predecessor, and this
    is the write that resolves them once every row is present. It touches no other
    column deliberately: the invalidation state that *accompanies* a supersession is
    already on the imported row and re-deriving it here would let a restore disagree
    with the artifact it is restoring.
    """
    conn.execute(
        update(t.memory)
        .where(t.memory.c.id == memory_id)
        .values(superseded_by_id=successor_id)
    )


def count_expired_memory_roots(
    conn: Connection, *, horizon: datetime, limit: int
) -> int:
    """How many expirable roots remain, counted no further than ``limit``.

    § A12's diagnostic half, and the bound is the whole reason it is a separate
    function from :func:`expired_memory_exists`. An operator refused an export needs
    to know whether one row is in the way or ten thousand, because those are
    different remedies; what they must not receive is an unbounded scan of the whole
    table inside a refusal path, or a number so exact it becomes a population count
    of the workspace. Counting to ``limit`` and stopping answers the first and
    withholds the second: a result equal to ``limit`` means "at least this many".

    The same predicate the sweep selects with, so the count and the work it describes
    cannot disagree — a count that included rows the sweep would never remove would
    tell an operator to wait for a batch that is never coming.
    """
    bounded = (
        select(t.memory.c.id)
        .where(_expired_workspace_memory(horizon))
        .limit(limit)
        .subquery()
    )
    return int(conn.execute(select(func.count()).select_from(bounded)).scalar_one())


@dataclass(frozen=True, slots=True)
class MemoryPurposeRow:
    memory_id: UUID
    purpose: str


def insert_memory_purpose(conn: Connection, row: MemoryPurposeRow) -> MemoryPurposeRow:
    conn.execute(
        insert(t.memory_purpose).values(memory_id=row.memory_id, purpose=row.purpose)
    )
    return row


def get_memory_purpose(
    conn: Connection, memory_id: UUID, purpose: str
) -> MemoryPurposeRow | None:
    mapping = (
        conn.execute(
            select(t.memory_purpose).where(
                t.memory_purpose.c.memory_id == memory_id,
                t.memory_purpose.c.purpose == purpose,
            )
        )
        .mappings()
        .one_or_none()
    )
    if mapping is None:
        return None
    return MemoryPurposeRow(memory_id=mapping["memory_id"], purpose=mapping["purpose"])


def list_memory_purposes(conn: Connection, memory_id: UUID) -> tuple[str, ...]:
    """Every purpose one memory carries, in vocabulary order.

    Ordered rather than left to the planner for the same reason
    :func:`list_memory_links` is: a derivation intersects these sets and a caller sees
    the result, so two runs of one request must not answer in two orders.
    """
    rows = conn.execute(
        select(t.memory_purpose.c.purpose)
        .where(t.memory_purpose.c.memory_id == memory_id)
        .order_by(t.memory_purpose.c.purpose)
    ).all()
    return tuple(str(row[0]) for row in rows)


@dataclass(frozen=True, slots=True)
class MemoryEntityRow:
    id: UUID
    kind: str
    name: str
    normalized_name: str
    ref: str | None
    created_at: datetime
    source_namespace: str | None
    external_source_key: str | None


def insert_memory_entity(conn: Connection, row: MemoryEntityRow) -> MemoryEntityRow:
    conn.execute(
        insert(t.memory_entity).values(
            id=row.id,
            kind=row.kind,
            name=row.name,
            normalized_name=row.normalized_name,
            ref=row.ref,
            created_at=row.created_at,
            source_namespace=row.source_namespace,
            external_source_key=row.external_source_key,
        )
    )
    return row


def get_memory_entity(conn: Connection, entity_id: UUID) -> MemoryEntityRow | None:
    mapping = (
        conn.execute(select(t.memory_entity).where(t.memory_entity.c.id == entity_id))
        .mappings()
        .one_or_none()
    )
    if mapping is None:
        return None
    return MemoryEntityRow(
        id=mapping["id"],
        kind=mapping["kind"],
        name=mapping["name"],
        normalized_name=mapping["normalized_name"],
        ref=mapping["ref"],
        created_at=mapping["created_at"],
        source_namespace=mapping["source_namespace"],
        external_source_key=mapping["external_source_key"],
    )


@dataclass(frozen=True, slots=True)
class MemoryMentionRow:
    memory_id: UUID
    entity_id: UUID
    role: str | None


def insert_memory_mention(conn: Connection, row: MemoryMentionRow) -> MemoryMentionRow:
    conn.execute(
        insert(t.memory_mention).values(
            memory_id=row.memory_id, entity_id=row.entity_id, role=row.role
        )
    )
    return row


def get_memory_mention(
    conn: Connection, memory_id: UUID, entity_id: UUID
) -> MemoryMentionRow | None:
    mapping = (
        conn.execute(
            select(t.memory_mention).where(
                t.memory_mention.c.memory_id == memory_id,
                t.memory_mention.c.entity_id == entity_id,
            )
        )
        .mappings()
        .one_or_none()
    )
    if mapping is None:
        return None
    return MemoryMentionRow(
        memory_id=mapping["memory_id"],
        entity_id=mapping["entity_id"],
        role=mapping["role"],
    )


def list_memory_mentions(conn: Connection, memory_id: UUID) -> tuple[UUID, ...]:
    """Every entity one memory mentions, in entity-id order.

    Ordered for the reason :func:`list_memory_links` is: the erasure path walks these
    and prunes an entity that loses its last mention, so two runs of one deletion
    must visit them in one order rather than the planner's.
    """
    rows = conn.execute(
        select(t.memory_mention.c.entity_id)
        .where(t.memory_mention.c.memory_id == memory_id)
        .order_by(t.memory_mention.c.entity_id)
    ).all()
    return tuple(row[0] for row in rows)


@dataclass(frozen=True, slots=True)
class MemoryLinkRow:
    memory_id: UUID
    ref: str
    relation: str
    created_at: datetime
    supersession_lineage: bool


def insert_memory_link(conn: Connection, row: MemoryLinkRow) -> MemoryLinkRow:
    conn.execute(
        insert(t.memory_link).values(
            memory_id=row.memory_id,
            ref=row.ref,
            relation=row.relation,
            created_at=row.created_at,
            supersession_lineage=row.supersession_lineage,
        )
    )
    return row


def get_memory_link(
    conn: Connection, memory_id: UUID, ref: str, relation: str
) -> MemoryLinkRow | None:
    mapping = (
        conn.execute(
            select(t.memory_link).where(
                t.memory_link.c.memory_id == memory_id,
                t.memory_link.c.ref == ref,
                t.memory_link.c.relation == relation,
            )
        )
        .mappings()
        .one_or_none()
    )
    if mapping is None:
        return None
    return MemoryLinkRow(
        memory_id=mapping["memory_id"],
        ref=mapping["ref"],
        relation=mapping["relation"],
        created_at=mapping["created_at"],
        supersession_lineage=mapping["supersession_lineage"],
    )


def list_memory_links(conn: Connection, memory_id: UUID) -> tuple[MemoryLinkRow, ...]:
    """Every link row owned by one memory, in composite-key order.

    Ordered rather than left to the planner because the eligibility service walks
    these in sequence and denies on the first one that fails: an unordered read would
    make *which* link a refusal came from depend on the plan, and two runs of the same
    request could then charge the shared reference budget differently.
    """
    rows = conn.execute(
        select(t.memory_link)
        .where(t.memory_link.c.memory_id == memory_id)
        .order_by(t.memory_link.c.ref, t.memory_link.c.relation)
    ).mappings()
    return tuple(
        MemoryLinkRow(
            memory_id=row["memory_id"],
            ref=row["ref"],
            relation=row["relation"],
            created_at=row["created_at"],
            supersession_lineage=row["supersession_lineage"],
        )
        for row in rows
    )


def list_memory_dependents(conn: Connection, ref: str) -> tuple[MemoryLinkRow, ...]:
    """Every link row that **names** ``ref``, in memory-id order.

    The inverse read of :func:`list_memory_links`, and the one the lifecycle closure
    walks: "which memories depend on this one" is a scan of the stored reference
    string, because ``memory_link.ref`` carries no foreign key — a reference is a
    value, and the row it names may belong to another module or to nothing at all.

    That is also why the rows survive their target's physical removal, which is what
    lets a deletion participant compute a closure **after** the owner has deleted
    the record it hangs off.

    Ordered by ``memory_id``, so a closure walks and locks rows in one deterministic
    order (§ A7) rather than the planner's.
    """
    rows = conn.execute(
        select(t.memory_link)
        .where(t.memory_link.c.ref == ref)
        .order_by(t.memory_link.c.memory_id, t.memory_link.c.relation)
    ).mappings()
    return tuple(
        MemoryLinkRow(
            memory_id=row["memory_id"],
            ref=row["ref"],
            relation=row["relation"],
            created_at=row["created_at"],
            supersession_lineage=row["supersession_lineage"],
        )
        for row in rows
    )


@dataclass(frozen=True, slots=True)
class MemoryEmbeddingRow:
    memory_id: UUID
    model_id: str
    dimensions: int
    vector: Sequence[float]
    embedded_at: datetime


def insert_memory_embedding(conn: Connection, row: MemoryEmbeddingRow) -> bool:
    """Write one embedding row, unless the memory already has one for this model;
    answer whether this call wrote it.

    The module's one writer of these rows is
    :meth:`~rheo_recallatron.retrieval.dense.DenseStrategy.index_many`, which the embed
    job and the rebuild both go through; synthetic fixtures still seed rows directly,
    as § A3's note allows. ``vector`` is passed to Postgres in pgvector's text form,
    which the column accepts without a client-side type; since revision
    ``0003_dense_retrieval`` the column is ``vector(384)``, so a row of any other width
    is refused by the database itself.

    **``ON CONFLICT (memory_id, model_id) DO NOTHING``, and that is safe only because of
    the vector-write handshake.** An embed job and a rebuild can both hold one memory
    ``FOR SHARE`` — the locks are compatible — and both embed it. Whichever writes
    second finds the other's row. Both read the same locked text, and a text change
    deletes a memory's vectors only after taking the row lock neither has released, so
    the row already there is the row this call would have written. Without this the
    second writer failed on the duplicate key, and for a rebuild that was the whole
    walk rolled back and requeued.
    """
    result = conn.execute(
        pg_insert(t.memory_embedding)
        .values(
            memory_id=row.memory_id,
            model_id=row.model_id,
            dimensions=row.dimensions,
            vector=vector_literal(row.vector),
            embedded_at=row.embedded_at,
        )
        .on_conflict_do_nothing(
            index_elements=[
                t.memory_embedding.c.memory_id,
                t.memory_embedding.c.model_id,
            ]
        )
        # ``RETURNING`` rather than ``rowcount``: this driver reports ``-1`` for an
        # ``INSERT``'s rowcount, and a skipped conflict returns no row at all.
        .returning(t.memory_embedding.c.memory_id)
    )
    return result.first() is not None


def get_memory_embedding(
    conn: Connection, memory_id: UUID, model_id: str
) -> MemoryEmbeddingRow | None:
    mapping = (
        conn.execute(
            select(t.memory_embedding).where(
                t.memory_embedding.c.memory_id == memory_id,
                t.memory_embedding.c.model_id == model_id,
            )
        )
        .mappings()
        .one_or_none()
    )
    if mapping is None:
        return None
    return MemoryEmbeddingRow(
        memory_id=mapping["memory_id"],
        model_id=mapping["model_id"],
        dimensions=mapping["dimensions"],
        vector=_vector_values(mapping["vector"]),
        embedded_at=mapping["embedded_at"],
    )


def delete_embeddings_for_other_models(conn: Connection, *, model_id: str) -> int:
    """Remove every embedding row written by a model other than ``model_id``.

    The rebuild's first prune: after the configured provider changes, the old model's
    vectors are not merely stale, they are in a different space, and a dense read must
    never compare against them. Answers how many rows went.
    """
    result = conn.execute(
        delete(t.memory_embedding).where(t.memory_embedding.c.model_id != model_id)
    )
    return int(result.rowcount)


def delete_all_memory_embeddings(conn: Connection) -> int:
    """Remove every embedding row in this workspace, whatever model wrote it.

    The rebuild's second prune, taken when the workspace's stamped embed input version
    is not the package's: a vector of the old composition is stale whichever model
    produced it.
    """
    return int(conn.execute(delete(t.memory_embedding)).rowcount)


@dataclass(frozen=True, slots=True)
class EmbeddingStateRow:
    """The workspace's one ``embedding_state`` row."""

    embed_input_version: int


def get_embedding_state(conn: Connection) -> EmbeddingStateRow | None:
    """The stamped embed input version, or ``None`` before the first rebuild."""
    version = conn.execute(
        select(t.embedding_state.c.embed_input_version).where(
            t.embedding_state.c.id.is_(True)
        )
    ).scalar_one_or_none()
    return None if version is None else EmbeddingStateRow(int(version))


def set_embedding_state(conn: Connection, *, embed_input_version: int) -> None:
    """Stamp the workspace's embed input version: create the one row, or update it."""
    statement = pg_insert(t.embedding_state).values(
        id=True, embed_input_version=embed_input_version
    )
    conn.execute(
        statement.on_conflict_do_update(
            index_elements=[t.embedding_state.c.id],
            set_={"embed_input_version": statement.excluded.embed_input_version},
        )
    )


def _live_memory() -> ColumnElement[bool]:
    """A memory an embedding is kept for: neither invalidated nor superseded.

    The one liveness the fill selects by, the coverage counts by and the embed job
    checks a row against, so the three cannot disagree about which rows ought to carry
    a vector.
    """
    return and_(
        t.memory.c.invalidated_at.is_(None), t.memory.c.superseded_by_id.is_(None)
    )


def _of_model(model_id: str) -> ColumnElement[bool]:
    """An embedding row ``model_id`` wrote: the one model filter the coverage, the fill
    and the dense arm's availability check all apply, so they cannot count different
    rows as "this model's"."""
    return t.memory_embedding.c.model_id == model_id


def _has_embedding(model_id: str) -> ColumnElement[bool]:
    return (
        select(t.memory_embedding.c.memory_id)
        .where(t.memory_embedding.c.memory_id == t.memory.c.id, _of_model(model_id))
        .exists()
    )


def is_live_memory(row: MemoryRow) -> bool:
    """:func:`_live_memory`, asked of a row already read."""
    return row.invalidated_at is None and row.superseded_by_id is None


# **The vector-write handshake.** A vector is only ever written for a memory row this
# transaction holds ``FOR SHARE``, from the read that supplied its text until the
# vector commits; and every writer that changes a row's text or liveness takes that
# row's lock (its ``UPDATE``) *before* it deletes the row's vectors. ``FOR SHARE``
# conflicts with that ``UPDATE``, so the two cannot interleave: an embed that got there
# first commits and the text change then deletes what it wrote, and an embed that came
# second waits and reads the new text. The two readers below are the only places a
# vector's source text is read.


def lock_memory_for_embedding(conn: Connection, memory_id: UUID) -> MemoryRow | None:
    """One memory, read ``FOR SHARE``, waiting out any writer that holds it.

    The embed job's read. Waiting is right for one row: a job holds no other row
    lock, so it cannot be one half of a deadlock, and a correction in flight is then
    read as corrected.
    """
    mapping = (
        conn.execute(
            select(t.memory)
            .where(t.memory.c.id == memory_id)
            .with_for_update(read=True)
        )
        .mappings()
        .one_or_none()
    )
    return None if mapping is None else _memory_row(mapping)


def list_memories_missing_embedding(
    conn: Connection, *, model_id: str, after: UUID | None, limit: int
) -> tuple[MemoryRow, ...]:
    """At most ``limit`` live memories with no row for ``model_id``, by id, after
    ``after`` — each read ``FOR SHARE``, and any row another writer holds skipped.

    Id-ordered so the caller's cursor is simply the last id it saw. The selection is
    "lacking a row", never "all", which is what makes a rerun of an interrupted fill
    safe and what keeps an ordinary embed job and a rebuild from both writing one
    memory's row.

    **Skipped, not waited for, because the rebuild holds every row it has read until
    its one commit.** A correction locks its target and then each dependant; a rebuild
    that waited for a locked row could be holding that correction's next dependant,
    and the two would deadlock. Skipping means the rebuild never waits on a writer, so
    no cycle can close through it. A skipped row is one whose text or liveness is
    changing right now: the walk leaves it unembedded, and the rebuild queues an embed
    job for it before it commits (:func:`list_memory_ids_missing_embedding`), which
    covers a change that rolls back as well as one that commits.
    """
    statement = select(t.memory).where(_live_memory(), ~_has_embedding(model_id))
    if after is not None:
        statement = statement.where(t.memory.c.id > after)
    rows = conn.execute(
        statement.order_by(t.memory.c.id)
        .limit(limit)
        .with_for_update(read=True, skip_locked=True)
    ).mappings()
    return tuple(_memory_row(mapping) for mapping in rows)


def list_memory_ids_missing_embedding(
    conn: Connection, *, model_id: str
) -> tuple[UUID, ...]:
    """Every live memory with no row for ``model_id``, by id — a plain read.

    The rebuild's last look, after its walk. No lock and no skip, on purpose: what it
    is for is exactly the rows the walk skipped because another writer held them, and a
    plain read sees each one's committed version without waiting for that writer.
    """
    rows = conn.execute(
        select(t.memory.c.id)
        .where(_live_memory(), ~_has_embedding(model_id))
        .order_by(t.memory.c.id)
    ).all()
    return tuple(row[0] for row in rows)


@dataclass(frozen=True, slots=True)
class EmbeddingCoverage:
    """How many live memories this workspace holds, and how many carry a vector from
    one model.

    Per workspace by construction: a workspace is a database, so there is no
    deployment-wide figure to compute and none is.
    """

    live: int
    embedded: int


def embedding_coverage(conn: Connection, *, model_id: str) -> EmbeddingCoverage:
    """Live memories, and those with a row for ``model_id``, in one statement."""
    live, embedded = conn.execute(
        select(func.count(), func.count().filter(_has_embedding(model_id)))
        .select_from(t.memory)
        .where(_live_memory())
    ).one()
    return EmbeddingCoverage(live=int(live), embedded=int(embedded))


def embedding_exists_for_model(conn: Connection, *, model_id: str) -> bool:
    """Whether this workspace holds any embedding row ``model_id`` wrote.

    The last condition of ``dense_available``. It separates a workspace no embed job
    has ever filled for this model (the dense arm cannot contribute) from partial
    coverage, where one memory lacks its row while others have theirs (it can).
    """
    return bool(
        conn.execute(
            select(
                select(t.memory_embedding.c.memory_id)
                .where(_of_model(model_id))
                .exists()
            )
        ).scalar_one()
    )


@dataclass(frozen=True, slots=True)
class EmbeddingPair:
    """Two memories whose vectors for one model clear a similarity floor.

    ``first`` sorts before ``second``, so a pair has exactly one spelling, and ``score``
    is their cosine similarity, ``1 - (a.vector <=> b.vector)``.
    """

    first: UUID
    second: UUID
    score: float


def dedup_candidate_ids(
    conn: Connection,
    *,
    conditions: Sequence[ColumnElement[bool]],
    model_id: str,
    scan_limit: int,
) -> tuple[UUID, ...]:
    """The bounded candidate set a dedup call starts from: at most ``scan_limit``
    memories that ``conditions`` admit and that hold a row for ``model_id``, newest
    first, ``recorded_at DESC, id``.

    ``conditions`` are the caller's row-local predicates over ``memory``, taken as a
    parameter because the service module that builds them imports this one. They
    narrow; they decide nothing. The caller runs full eligibility over what comes back
    and hands :func:`nearest_embedding_pairs` only the memories it may read.

    **This is where the bound is applied, before eligibility,** so a memory the SQL
    admits and eligibility then denies (one with a link the caller cannot resolve)
    still holds one of the places. That keeps both the eligibility walk and the scan
    at a constant, the way recall's own scan bound does.
    """
    return tuple(
        conn.execute(
            select(t.memory.c.id)
            .where(_has_embedding(model_id), *conditions)
            .order_by(t.memory.c.recorded_at.desc(), t.memory.c.id)
            .limit(scan_limit)
        ).scalars()
    )


def nearest_embedding_pairs(
    conn: Connection,
    *,
    memory_ids: Sequence[UUID],
    model_id: str,
    floor: float,
) -> tuple[EmbeddingPair, ...]:
    """Among exactly ``memory_ids``, each one's nearest other, where the two clear
    ``floor``.

    The caller chooses the set: ``dedup_candidates`` passes the memories of its bounded
    candidate set (:func:`dedup_candidate_ids`) that it has already found the caller
    may read, so a memory the caller cannot read never takes a readable one's
    nearest-neighbour place. One statement, three steps:

    1. **The candidate vectors:** ``model_id``'s row for each of ``memory_ids``,
       materialized, so both sides of the join below read the same set.
    2. **One ``CROSS JOIN LATERAL``** (rendered ``JOIN LATERAL ... ON true``): for each
       candidate, its single nearest *other* candidate by ``vector <=> vector``, ties
       broken by id, kept only where ``1 - (a.vector <=> b.vector) >= floor``.
    3. **Folded and sorted:** a pair both members found from their own side is one
       pair, spelled ``(least, greatest)``; the answer runs by score descending, then
       ``(first, second)``. A canonical memory reference is a fixed prefix and the
       UUID's hex, so that order is the order of the references too.

    **This is a quadratic scan over the set, and it is meant to be.** pgvector's HNSW
    index answers "nearest in the table" and then filters; it cannot answer "nearest
    within this arbitrary filtered subset", so the set is materialized and every
    distance is computed directly. 500 candidates make 124,750 distinct pairs, and the
    lateral measures each one from both ends: 249,500 cosine distances at 384
    dimensions, of the order of 10^8 float operations per call. ``DEDUP_SCAN_LIMIT``
    holding the set at 500, and the eligibility walk before it at 500 evaluations, is
    the *entire* argument for ``dedup_candidates`` being a ``READ`` operation rather
    than a ``long_running`` one, so nobody raises it without revisiting that class.

    **The bound is also a recall boundary, not only a cost bound.** The set comes from
    the newest ``DEDUP_SCAN_LIMIT`` by ``recorded_at``: at 500, the 501st-newest memory
    is never compared with anything and a duplicate pair straddling that position is
    never proposed. That is the insertion-order blind spot binding constraint 6 chose
    vector neighbourhoods to close, moved to recency rather than removed. It is carried
    open, not fixed here.
    """
    if len(memory_ids) < 2:
        return ()
    candidate = (
        select(
            t.memory_embedding.c.memory_id.label("memory_id"),
            t.memory_embedding.c.vector.label("vector"),
        )
        .where(_of_model(model_id), t.memory_embedding.c.memory_id.in_(memory_ids))
        .cte("dedup_candidate")
        .prefix_with("MATERIALIZED")
    )
    a = candidate.alias("a")
    b = candidate.alias("b")
    distance = a.c.vector.op("<=>", return_type=Float)(b.c.vector)
    nearest = (
        select(b.c.memory_id.label("memory_id"), distance.label("distance"))
        .where(b.c.memory_id != a.c.memory_id)
        .order_by(distance, b.c.memory_id)
        .limit(1)
        .lateral("nearest")
    )
    # The dense arm's expression, over two stored vectors instead of one and a query:
    # a similarity, compared ``>=``, never the distance against the floor.
    similarity = literal_column("1", Float) - nearest.c.distance
    first = func.least(a.c.memory_id, nearest.c.memory_id, type_=a.c.memory_id.type)
    second = func.greatest(a.c.memory_id, nearest.c.memory_id, type_=a.c.memory_id.type)
    score = func.max(similarity).label("score")
    rows = conn.execute(
        select(first.label("first"), second.label("second"), score)
        .select_from(a.join(nearest, true()))
        .where(similarity >= bindparam("dedup_pair_floor", floor, type_=Float))
        .group_by(first, second)
        .order_by(score.desc(), first, second)
    ).all()
    return tuple(
        EmbeddingPair(first=row.first, second=row.second, score=float(row.score))
        for row in rows
    )


def analyze_memory(conn: Connection) -> None:
    """``ANALYZE`` the memory table, in the caller's transaction.

    The rebuild's success path. Useful for the dense path's planner after a walk that
    touched every row; it is not what keeps the lexical builder's statistics present,
    which is migration ``0003_dense_retrieval``'s autovacuum setting.
    """
    conn.execute(text(f"ANALYZE {t.memory.schema}.{t.memory.name}"))


def vector_literal(values: Sequence[float]) -> str:
    """pgvector's own text form, ``[1,2,3]``: how a stored vector is written and how the
    dense arm binds its query vector, so the two cannot be spelled differently."""
    return "[" + ",".join(repr(float(value)) for value in values) + "]"


def _vector_values(literal: object) -> tuple[float, ...]:
    """The inverse of :func:`vector_literal` for the text Postgres hands back."""
    stripped = str(literal).strip().removeprefix("[").removesuffix("]")
    if not stripped:
        return ()
    return tuple(float(part) for part in stripped.split(","))


@dataclass(frozen=True, slots=True)
class SourceReceiptRow:
    representation_type: str
    source_namespace: str
    external_source_key: str
    record_id: UUID | None
    payload_digest: bytes
    state: str
    producer_kind: str
    authority_id: UUID
    principal_account_id: UUID | None
    audience_kind: str
    audience_id: UUID | None
    bound_purpose: str | None
    source_recorded_at: datetime | None
    source_expires_at: datetime | None


def insert_source_receipt(conn: Connection, row: SourceReceiptRow) -> SourceReceiptRow:
    conn.execute(
        insert(t.source_receipt).values(
            representation_type=row.representation_type,
            source_namespace=row.source_namespace,
            external_source_key=row.external_source_key,
            record_id=row.record_id,
            payload_digest=row.payload_digest,
            state=row.state,
            producer_kind=row.producer_kind,
            authority_id=row.authority_id,
            principal_account_id=row.principal_account_id,
            audience_kind=row.audience_kind,
            audience_id=row.audience_id,
            bound_purpose=row.bound_purpose,
            source_recorded_at=row.source_recorded_at,
            source_expires_at=row.source_expires_at,
        )
    )
    return row


def set_source_receipt_state(
    conn: Connection,
    representation_type: str,
    source_namespace: str,
    external_source_key: str,
    *,
    state: str,
) -> bool:
    """Move one receipt to a terminal ``state``; answer whether a row was matched.

    The **only** column this updates. Every other column on the row is immutable
    authority context or the digest of the evidence it was accepted under, and
    rewriting either would make a receipt say the unit was accepted under conditions
    it was not — which is the one thing the row exists to remember.
    """
    result = conn.execute(
        update(t.source_receipt)
        .where(
            t.source_receipt.c.representation_type == representation_type,
            t.source_receipt.c.source_namespace == source_namespace,
            t.source_receipt.c.external_source_key == external_source_key,
        )
        .values(state=state)
    )
    return result.rowcount == 1


def get_source_receipt(
    conn: Connection,
    representation_type: str,
    source_namespace: str,
    external_source_key: str,
) -> SourceReceiptRow | None:
    mapping = (
        conn.execute(
            select(t.source_receipt).where(
                t.source_receipt.c.representation_type == representation_type,
                t.source_receipt.c.source_namespace == source_namespace,
                t.source_receipt.c.external_source_key == external_source_key,
            )
        )
        .mappings()
        .one_or_none()
    )
    if mapping is None:
        return None
    return SourceReceiptRow(
        representation_type=mapping["representation_type"],
        source_namespace=mapping["source_namespace"],
        external_source_key=mapping["external_source_key"],
        record_id=mapping["record_id"],
        payload_digest=bytes(mapping["payload_digest"]),
        state=mapping["state"],
        producer_kind=mapping["producer_kind"],
        authority_id=mapping["authority_id"],
        principal_account_id=mapping["principal_account_id"],
        audience_kind=mapping["audience_kind"],
        audience_id=mapping["audience_id"],
        bound_purpose=mapping["bound_purpose"],
        source_recorded_at=mapping["source_recorded_at"],
        source_expires_at=mapping["source_expires_at"],
    )


def export_memory_rows(conn: Connection) -> tuple[MemoryRow, ...]:
    """Every memory, ascending by id, ``search_tsv`` excluded by the row shape."""
    return tuple(
        _memory_row(mapping)
        for mapping in conn.execute(select(t.memory).order_by(t.memory.c.id)).mappings()
    )


def export_memory_purpose_rows(conn: Connection) -> tuple[MemoryPurposeRow, ...]:
    return tuple(
        MemoryPurposeRow(memory_id=row.memory_id, purpose=str(row.purpose))
        for row in conn.execute(
            select(t.memory_purpose).order_by(
                t.memory_purpose.c.memory_id, t.memory_purpose.c.purpose
            )
        ).all()
    )


def export_memory_entity_rows(conn: Connection) -> tuple[MemoryEntityRow, ...]:
    return tuple(
        MemoryEntityRow(
            id=row.id,
            kind=str(row.kind),
            name=str(row.name),
            normalized_name=str(row.normalized_name),
            ref=None if row.ref is None else str(row.ref),
            created_at=row.created_at,
            source_namespace=(
                None if row.source_namespace is None else str(row.source_namespace)
            ),
            external_source_key=(
                None
                if row.external_source_key is None
                else str(row.external_source_key)
            ),
        )
        for row in conn.execute(
            select(t.memory_entity).order_by(t.memory_entity.c.id)
        ).all()
    )


def export_memory_mention_rows(conn: Connection) -> tuple[MemoryMentionRow, ...]:
    return tuple(
        MemoryMentionRow(
            memory_id=row.memory_id,
            entity_id=row.entity_id,
            role=None if row.role is None else str(row.role),
        )
        for row in conn.execute(
            select(t.memory_mention).order_by(
                t.memory_mention.c.memory_id, t.memory_mention.c.entity_id
            )
        ).all()
    )


def export_memory_link_rows(conn: Connection) -> tuple[MemoryLinkRow, ...]:
    return tuple(
        MemoryLinkRow(
            memory_id=row.memory_id,
            ref=str(row.ref),
            relation=str(row.relation),
            created_at=row.created_at,
            supersession_lineage=bool(row.supersession_lineage),
        )
        for row in conn.execute(
            select(t.memory_link).order_by(
                t.memory_link.c.memory_id,
                t.memory_link.c.ref,
                t.memory_link.c.relation,
            )
        ).all()
    )


def export_source_receipt_rows(conn: Connection) -> tuple[SourceReceiptRow, ...]:
    """Every receipt, in primary-key order, whatever its state.

    Retained history travels: § A12 names active, noop, denied and terminal
    identity-only receipts together, because a restored deployment that lost the
    terminal ones could replay an accepted source unit into a second memory.
    """
    return tuple(
        SourceReceiptRow(
            representation_type=str(row.representation_type),
            source_namespace=str(row.source_namespace),
            external_source_key=str(row.external_source_key),
            record_id=row.record_id,
            payload_digest=bytes(row.payload_digest),
            state=str(row.state),
            producer_kind=str(row.producer_kind),
            authority_id=row.authority_id,
            principal_account_id=row.principal_account_id,
            audience_kind=str(row.audience_kind),
            audience_id=row.audience_id,
            bound_purpose=None if row.bound_purpose is None else str(row.bound_purpose),
            source_recorded_at=row.source_recorded_at,
            source_expires_at=row.source_expires_at,
        )
        for row in conn.execute(
            select(t.source_receipt).order_by(
                t.source_receipt.c.representation_type,
                t.source_receipt.c.source_namespace,
                t.source_receipt.c.external_source_key,
            )
        ).all()
    )
