// generated by `rheo web compose`; do not edit
import type { ComposedModule } from "@rheo-stream/web-contract/screen";
import * as recallatronWeb from "@rheo-stream/recallatron-web";

export const MODULES = [
  {
    id: "recallatron",
    surface: "recallatron",
    navigation: [
      { id: "memory", label: "Memory", path: "/", roles: ["member", "owner"] },
      { id: "search", label: "Search memory", path: "/search", roles: ["member", "owner"] },
      { id: "duplicates", label: "Possible duplicates", path: "/duplicates", roles: ["member", "owner"] },
    ],
    routes: [
      { id: "browse", path: "/", screen: recallatronWeb.screens.browse },
      { id: "search", path: "/search", screen: recallatronWeb.screens.search },
      { id: "item", path: "/item", screen: recallatronWeb.screens.item },
      { id: "duplicates", path: "/duplicates", screen: recallatronWeb.screens.duplicates },
    ],
    recordViews: [],
    forms: [],
    searchProviders: [
      { id: "recall", operation: "recallatron.memory.recall" },
    ],
  },
] as const satisfies readonly ComposedModule[];
