// generated by `rheo web compose`; do not edit
import type { ComposedModule } from "@rheo-stream/web-contract/screen";
import * as leadsWeb from "@rheo-stream/leads-web";
import * as recallatronWeb from "@rheo-stream/recallatron-web";

export const MODULES = [
  {
    id: "leads",
    surface: "leads",
    navigation: [
      { id: "leads", label: "Leads", path: "/", roles: ["member", "owner"] },
    ],
    routes: [
      { id: "list", path: "/", screen: leadsWeb.screens.list },
      { id: "board", path: "/board", screen: leadsWeb.screens.board },
      { id: "detail", path: "/detail", screen: leadsWeb.screens.detail },
      { id: "capture", path: "/capture", screen: leadsWeb.screens.capture },
      { id: "receipt", path: "/receipt", screen: leadsWeb.screens.receipt },
      { id: "connections", path: "/connections", screen: leadsWeb.screens.connections },
    ],
    recordViews: [],
    forms: [
      { operation: "leads.intake.capture", component: leadsWeb.components.ActionForm },
      { operation: "leads.pipeline.create", component: leadsWeb.components.ActionForm },
      { operation: "leads.connection.set_routing", component: leadsWeb.components.ActionForm },
      { operation: "leads.opportunity.create_from_observation", component: leadsWeb.components.ActionForm },
      { operation: "leads.opportunity.update", component: leadsWeb.components.ActionForm },
      { operation: "leads.opportunity.transition", component: leadsWeb.components.ActionForm },
      { operation: "leads.opportunity.add_note", component: leadsWeb.components.ActionForm },
      { operation: "leads.qualification.assess", component: leadsWeb.components.ActionForm },
      { operation: "leads.followup.draft", component: leadsWeb.components.ActionForm },
    ],
    searchProviders: [],
    readOperations: [
      "leads.connection.health",
      "leads.contact_permission.check",
      "leads.handoff.get",
      "leads.intake.receipt",
      "leads.observation.get",
      "leads.opportunity.get",
      "leads.opportunity.list",
      "leads.opportunity.search",
      "leads.pipeline.list",
      "leads.qualification.list",
      "leads.ui.catalog",
    ],
    submitOperations: [
      "leads.connection.set_routing",
      "leads.followup.draft",
      "leads.intake.capture",
      "leads.opportunity.add_note",
      "leads.opportunity.create_from_observation",
      "leads.opportunity.transition",
      "leads.opportunity.update",
      "leads.pipeline.create",
      "leads.qualification.assess",
    ],
  },
  {
    id: "recallatron",
    surface: "recallatron",
    navigation: [
      { id: "memory", label: "Memory", path: "/", roles: ["member", "owner"] },
    ],
    routes: [
      { id: "browse", path: "/", screen: recallatronWeb.screens.browse },
      { id: "search", path: "/search", screen: recallatronWeb.screens.search },
      { id: "item", path: "/item", screen: recallatronWeb.screens.item },
      { id: "history-item", path: "/history/item", screen: recallatronWeb.screens.historyItem },
      { id: "duplicates", path: "/duplicates", screen: recallatronWeb.screens.duplicates },
    ],
    recordViews: [],
    forms: [],
    searchProviders: [
      { id: "recall", operation: "recallatron.memory.recall" },
    ],
    readOperations: [
      "recallatron.embedding.coverage",
      "recallatron.entity.get",
      "recallatron.entity.list",
      "recallatron.history.get",
      "recallatron.history.search",
      "recallatron.memory.dedup_candidates",
      "recallatron.memory.get",
      "recallatron.memory.read",
      "recallatron.memory.recall",
    ],
    submitOperations: [],
  },
] as const satisfies readonly ComposedModule[];
